sirian_suggest:
    form_options:
        widget: select2_v3
        attr:
            placeholder: "Search..."

    orm:
        user:
            class: App\Entity\User
            property: username
            search:
                email: ~
                username: ~

        product:
            class: App\Entity\Product
            property: title