sonata_admin:
    title: 'My-shop admin'
    title_logo: http://rold.at.ua/skillup/myshop.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_javascripts:
            - js/admin.js
        extra_stylesheets:
            - css/admin.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
