vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: vich_uploader.namer_uniqid
            directory_namer: vich_uploader.directory_namer_subdir
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: vich_uploader.namer_uniqid
            directory_namer: vich_uploader.directory_namer_subdir
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true